### ISSUE TITLE
use protoc-jar?

### ISSUE THREAD

**Issue by os72** [sbt/sbt-protobuf#28]
Check out protoc-jar perhaps (I'm the author), it can eliminate protoc dependency in most cases. I use it in maven builds
https://github.com/os72/protoc-jar
https://github.com/os72/protoc-jar-maven-plugin

**Comment by gseitz** [comment]
Since 0.4.0, it's possible to make use of your protoc-jar project. However, sbt-protobuf cannot depend on it directly, as that would fix the version of protoc used for all builds.

For work, I created an internal clone that contains the latest binaries for all 2.x releases of protoc. The main class expects as first parameter the protoc version that should be used. Would you be interested in a pull request?

**Comment by os72** [comment]
Yes, sounds good, thanks. That could actually be the master version

**Comment by xuwei-k** [comment]
added some test codes with protoc-jar https://github.com/sbt/sbt-protobuf/commit/df7766be03076bbe34fee

**Comment by rgruener** [comment]
Is there any status on this? It would be quite useful to not have to worry about installing the protoc binaries locally

**Comment by rgruener** [comment]
Actually looking into this it should be possible. Any examples using protobuf-jar with a multimodule project?

**Comment by xuwei-k** [comment]
https://github.com/sbt/sbt-protobuf/pull/67
