### ISSUE TITLE
Is this project active? 

### ISSUE THREAD

**Issue by xuwei-k** [sbt/sbt-protobuf#36]
ping @gseitz

**Comment by gseitz** [comment]
I don't have much time to work on this project anymore. I merged a couple of pull requests, but I cannot publish to bintray from work. Any other maintainer who can is welcome to do so.

**Comment by xuwei-k** [comment]
I see. thank you for your response. I want to be a maintainer :hand:

**Comment by gseitz** [comment]
Cool, thanks a lot. I added you as collaborator. I hope that's enough for you to be able to push commits/tags to the repository.

**Comment by gseitz** [comment]
Btw, I took the bintray configuration from sbt-release, which was done by @jroper. I hope it works how it is set up now.

**Comment by eed3si9n** [comment]
bintray-sbt sets `bintrayOrganization` to `None` by default because that's the normal workflow for a sbt plugin that's maintained by individuals. The author first publishes to his/her repository, and then send us a link request. See http://www.scala-sbt.org/0.13/docs/Bintray-For-Plugins.html#Linking+your+package+to+the+sbt+organization

If you guys want to maintain this plugin together then you can use `Some("sbt")`, which allows you to directly publish into bintray.com/sbt organization. But that means you two need to become a member of the Bintray sbt organization. Invitation is in your inbox. Happy hacking.

**Comment by xuwei-k** [comment]
Thanks! I will release 0.5.0

**Comment by gseitz** [comment]
Thanks @eed3si9n.

**Comment by xuwei-k** [comment]
0.5.0 released https://bintray.com/sbt/sbt-plugin-releases/sbt-protobuf/0.5.0/view
